name: Deploy to Amazon CloudFront

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  NODE_VERSION: [ 18.x ]

jobs:
  build:
    name: Amazon CloudFront Deploy
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - run: echo "This is a test run for GitHub Actions for ${{ github.repository }}. Hopefully this test finally works."
